### ISSUE TITLE
Can't reindex with algolia search

### ISSUE THREAD

**Issue by dungnv** [algolia/algoliasearch-magento-2#10]
Algolia Search Products index is locked by another reindex process. Skipping.
Algolia Search Categories index is locked by another reindex process. Skipping.
PHP Fatal error:  Call to a member function initIndex() on null in vendor/algolia/algoliasearch-magento-2/Helper/AlgoliaHelper.php on line 31

**Comment by JanPetr** [comment]
Hey @dungnv, the error message means that you did not provide Algolia API credentials. You need to set them in Configuration.

**Comment by vkranjith** [comment]
Hey @JanPetr, I am getting similar issue.

**Algolia Search Products index is locked by another reindex process. Skipping.**
Algolia Search Categories index has been rebuilt successfully in 00:00:01
Algolia Search Pages index has been rebuilt successfully in 00:00:00
Algolia Search Suggestions index has been rebuilt successfully in 00:00:00
Algolia Search Suggestions index has been rebuilt successfully in 00:00:00
Algolia Search Queue Runner index has been rebuilt successfully in 00:00:00
Design Config Grid index has been rebuilt successfully in 00:00:10
...

What could be the issue here?
