### ISSUE TITLE
Boolean facets on search page not working with Instant Search disabled

### ISSUE THREAD

**Issue by lumnn** [algolia/algoliasearch-magento-2#1006]
**Bug: Steps to reproduce**

1. Disable Instant Search Results Page
2. Add Yes/No attributes and add it into facets list
3. Go to search result page (type generic phrase in search and press enter)
4. Check Yes/No attribute to filter result

Filter will work if in search URL, value of `1` or `0` is replaced to `Yes` or `No`.

Changing templates, or classes that are responsible for building the filter URL doesn't seem to be a solution as the same code is used for category filtering, where `1`/`0` values are expected.

This is related to one of the old issues I've posted here in the past #767

Although back there it caused me an issue in the templates, now it causes part of the search doesn't work, so that's why I decided to report it.

I've checked that on both versions 1.13 and 2.0. Also the same issue seems to be happening on default and custom theme. I didn't check on clean Magento install, although I've disabled the modules I believe affected filtering/search in any way.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
