### ISSUE TITLE
Problem during bundle products indexation

### ISSUE THREAD

**Issue by kignaciuk** [algolia/algoliasearch-magento-2#1008]
I have noticed some problems during manual indexation process after fresh extension installation via composer version. 2.0.0.

Magento: 2.3.4

command:
`$ php bin/magento indexer:reindex algolia_products algolia_categories algolia_pages algolia_suggestions algolia_additional_sections`

result:
`PHP Fatal error:  Uncaught Error: Cannot use object of type Magento\Bundle\Model\ResourceModel\Selection\Collection\Interceptor as array in /var/www/html/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php:566
Stack trace:
#0 /var/www/html/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php(510): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->getSubProducts(Object(Magento\Catalog\Model\Product\Interceptor))
#1 /var/www/html/vendor/algolia/algoliasearch-magento-2/Helper/Data.php(509): Algolia\AlgoliaSearch\Helper\Entity\ProductHelper->getObject(Object(Magento\Catalog\Model\Product\Interceptor))
#2 /var/www/html/vendor/algolia/algoliasearch-magento-2/Helper/Data.php(638): Algolia\AlgoliaSearch\Helper\Data->getProductsRecords(1, Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor), NULL)
#3 /var/www/html/vendor/algolia/algoliasearch-magento-2/Helper/Data.php(350): Algolia\AlgoliaSearch\Helper\Data->rebuildStoreProductIndexPage(1, Object(Magento\Catalog\Model\Resource in /var/www/html/vendor/algolia/algoliasearch-magento-2/Helper/Entity/ProductHelper.php on line 566`

The problem is related to bundle products which are out of stock.

In file: https://github.com/algolia/algoliasearch-magento-2/blob/develop/Helper/Entity/ProductHelper.php 
in line 553 you get collection:
`$subProducts = $typeInstance->getSelectionsCollection($typeInstance->getOptionsIds($product), $product);`
and next in line 566
`unset($subProducts[$index]);`
you try to treat object as array which results in a error message

**Comment by KernelKorn** [comment]
I've noticed this issue too. Adding `getItems()` seems to have fixed the issue for me. You'll just have to create a composer patch until Algolia fixes it. 

```$subProducts = $typeInstance->getSelectionsCollection($typeInstance->getOptionsIds($product), $product)->getItems();```

**Comment by bsuravech** [comment]
Hi @kignaciuk and @KernelKorn ! 

Thanks for submitting an issue. After reviewing the case and looking at your suggestion @KernelKorn, the solution is to append `->getItems()` after the collection fetch so that the returned type is an array. We will create a PR for this correction. Once it has been attached to the issue, please feel free to patch with it until the next release. 

Thanks!

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, the related PR is still existing and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
