### ISSUE TITLE
Incorrect URL Indexed for CMS Pages in Multi-Store Configuration

### ISSUE THREAD

**Issue by NicholasRoge** [algolia/algoliasearch-magento-2#1009]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

CMS pages are always indexed with the base URL of the default store.

**Bug: What is the expected behavior?**

CMS pages should be indexed with the base URL of the store with which they are associated.

**Bug: What is the proposed solution?**

`setScope` should be called on the `frontendUrlBuilder` object instead of `setStore` in [\\Algolia\\AlgoliaSearch\\Helper\\Entity\\PageHelper#getStores](https://github.com/algolia/algoliasearch-magento-2/blob/develop/Helper/Entity/PageHelper.php#L132).  

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento Version: EE 2.3.4

Algolia Extension Version:  1.13.1

**Comment by palviggi-flagbit** [comment]
I just had to solve the exact same issue, on Algolia Extension 2.0.0

**Comment by palviggi-flagbit** [comment]
I also had a problem where it would use the domain from another store. To fix that I'm injecting `\Magento\Framework\UrlFactory` instead of `\Magento\Framework\UrlInterface` and using create at the start of the loop to get a clean UrlInterface instance. That's the way I found it being used inside magento code

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, the related PR is still existing and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
