### ISSUE TITLE
Error on Setup Upgrade

### ISSUE THREAD

**Issue by indunil15** [algolia/algoliasearch-magento-2#1011]
**Do you want to request a *feature* or report a *bug*?** This is a Bug in the Aloglia 1.13.1 version.

**Bug: What is the current behavior?**
While doing the setup upgrade it produces an error with

>  Upgrading data.. Hosts unreachable: 

**Bug: What is the expected behavior?** Should run the setup upgrade without any issue.

**Bug: What is the proposed solution?**
To replicate this issue need to have followings in the setup upgrade.
- Indexer need to set to update on save
- Aloglia API key and other credentials need to be wrong or unreachable host
- There should be a setup script to run in the setup: upgrade 

The issue triggers from 

> vendor/algolia/algoliasearch-magento-2/Model/Indexer/ProductObserver.php

`/**
     * @param Action $subject
     * @param Action|null $result
     * @param array $productIds
     *
     * @return Action
     */
    public function afterUpdateAttributes(Action $subject, Action $result = null, $productIds)
    {
        if (!$this->indexer->isScheduled()) {
            $this->indexer->reindexList(array_unique($productIds));
        }

        return $result;
    }`
The above function will trigger the while update of the product attributes and then try to trigger the indexing.
We think indexing should not mix with the setup: upgrade and it will cost an error while setup some modules and Algolia should provide a good error message to track down this kind of issue.

Error throws from the file

> vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php
`throw new AlgoliaConnectionException('Hosts unreachable: '.implode(',', $exceptions));`

I think it is better to come with more descriptive errors and should log this error.

Hope proposed fix in the top and will try to add a patch for our work currently. This can be definity issue for production servers if someone uses with an update on save. (Magento not recommend to do update on save, but have see some small sites do it)

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.3.5-p1 community 
Aligolia 1.13.1

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
