### ISSUE TITLE
After install Algolia does not display products in search and in catalog page magneto 2.3

### ISSUE THREAD

**Issue by Ghadawi** [algolia/algoliasearch-magento-2#1022]
I have install Algolia extension using composer and i run the index
the Algolia search doesn't display products only it display categories in seacrh

I have follow the document help to install the extension 
please help how to make sure the search work properly ?

I am using trial account

**Comment by bsuravech** [comment]
Hi @Ghadawi,

Thanks for reaching out to us. In order to better assist you with your issue with indexing, can you please send any logging, outputs, or details over to [support@algolia.com](mailto:support@algolia.com). Please let us know what version of the extension you are using, what Magento version, and if you have the Indexing Queue enabled. 

From there we are able to attach your account and if needed request further information from you securely. I will close the issue here and hope to see your issue in our inbox. Thanks!
