### ISSUE TITLE
Custom data is missed in response 

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#108]
I`ve added  custom data in observer for event  algolia_product_index_before and It `s present in Algolia admin http://prntscr.com/d7y9gb but this data is missed in queries response http://prntscr.com/d7yaod. I`ve tested one App - Data is present in Magento 1 but not it isn`t  shown on Magento 2. Algolia module version 1.0.3.

**Comment by JanPetr** [comment]
Hello @vmalyk,
can you send me here the whole value of "params" attribute from the response? In the screenshot you pasted is only part of it. Thanks!

And is it happening on autocomplete or instant search page? Or on both? Thanks for the answer in advance.

**Comment by vmalyk** [comment]
Hi,
1. Params value:
query=ipa&hitsPerPage=9&maxValuesPerFacet=10&page=0&facets=%5B%22color%22%2C%22price.NOK.default%22%2C%22categories.level0%22%5D&tagFilters=&numericFilters=%5B%22visibility_search%3D1%22%5D&attributesToRetrieve=%5B%22name%22%2C%22path%22%2C%22categories%22%2C%22color%22%2C%22sku%22%2C%22ordered_qty%22%2C%22stock_qty%22%2C%22rating_summary%22%2C%22created_at%22%2C%22objectID%22%2C%22name%22%2C%22url%22%2C%22visibility_search%22%2C%22visibility_catalog%22%2C%22categories%22%2C%22categories_without_path%22%2C%22thumbnail_url%22%2C%22image_url%22%2C%22in_stock%22%2C%22type_id%22%2C%22price.NOK.default%22%2C%22price.NOK.default_formated%22%2C%22price.NOK.group_1%22%2C%22price.NOK.group_1_formated%22%2C%22price.NOK.special_from_date%22%2C%22price.NOK.special_to_date%22%5D
2. It`s for instant search

Thanks for help.

**Comment by JanPetr** [comment]
Thanks for the respond @vmalyk,
I can see where the issue is. For security reason, the extension generates Secured API key and set attributes to retrieve directly to the API key. You can see it [here](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/templates/internals/configuration.phtml#L109), [here](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/AlgoliaHelper.php#L80-L83) and [here](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/ConfigHelper.php#L479-L519).

The issue is it does not take into account external attributes currently and there is no way how specify them. Will think of the best way how to handle that. If you'll have any idea, let me know.

**Comment by vmalyk** [comment]
Hi @JanPetr,
How about to add event into [this method](https://github.com/algolia/algoliasearch-magento-2/blob/master/Helper/ConfigHelper.php#L479-L519) and devs will add attribute codes from observers?

**Comment by JanPetr** [comment]
Probably the best solution @vmalyk, implemented in #112
