### ISSUE TITLE
Feature/Enhancement Category and Search Display

### ISSUE THREAD

**Issue by richdynamix** [algolia/algoliasearch-magento-2#116]
Hi Guys,

Is there anything in your roadmap to allow users to switch from grid view to list view as per default Magento functionality. We have a customer who is complaining that this is removed and we may need to implement something custom for this.

I didn't want us wasting time with a fork if it is planned for the near future.

**Comment by JanPetr** [comment]
Hey @richdynamix,
I'' probably disappoint you here. Switching view types is not something we plan to implement. At least not in the near future.

But it shouldn't be hard to add the feature on your side with adding some custom CSS and JS for switching it. If there'll be differences in displayed information, you'll have to tweak (override) just hit template.

**Comment by richdynamix** [comment]
Yeah I was thinking of implementing something custom using just CSS and JS. Essentially if we have already indexed the data to be viewable on listing pages then we can simply hide non essential information between views.

I am curious why you have no plans to implement and list view? Is there a particular reason/issue I should be aware of before embarking down the rabbit hole 😜

**Comment by JanPetr** [comment]
Hello @richdynamix,
no, there shouldn't be any hidden issues or something like that.

But it's not that common feature and only limited number of users will actually use it. And it brings a bit more complexity to the code and needs to maintain another product view.
And it's not that complex to implement it on user's side as you usually have to adapt the look and feel to your custom theme.

So that's why we won't implement such a feature now. I believe you understand.
