### ISSUE TITLE
Missing records from Algolia

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-magento-2#124]
**Prerequisites:**
- Disabled indexing queue
- set all indexer mode to "update on save"

**Steps to reproduce missing categories:**
1. Create active category without selecting any products
2. Edit previously created category and select at least one product and
save - at this point category is still missing in Algolia index
3. Save again the same category - entity is present in Algolia index

**Steps to reproduce missing products:**
1. Create active new product with stock - after save, product is not at Algolia
2. Save again the same product (entity is present in Algolia index)

**Comment by sammarcus** [comment]
@JanPetr Hi, I think I might be experiencing this with products. I have several hundred products that are not appearing in Algolia index, and can make one immediately appear individually by doing nothing more than going to the individual product in clicking "Save" in Magento. Because it appears in the index by doing nothing more than simply clicking save, I am concluding that the attributes are set correctly (visibility, stock etc) or else it would first require some tweaking.

Normally when items are left out of the index, I've always been able to fix it through changing attributes, adding required ones that were left out, etc. I've inspected the assigned attributes in `catalog_product_entity_int` between a product showing in the index and one that is not showing in the index, and they are identical. I can't seem to identify what is being changed when I click Save that would cause it to be indexed but would not index otherwise. Of course, individually saving each one is not practical. Do you have any ideas how to track down why these aren't getting indexed?

I'ved tried clearing my algolia products index out and reindexing without success (and my queue is off). I'm running M2 2.1.7 and 1.1.0 of this extension. If you think this might be fixed in 1.2.0 I can give it a go but won't be able to use it in production as we're version locked due to an ongoing implementation with another project.

**Comment by sammarcus** [comment]
@JanPetr Do you have any ideas around this?

Thank you!

**Comment by sammarcus** [comment]
Hi, just checking in if anyone has seen my comment above from Aug 9?

**Comment by JanPetr** [comment]
Hello @sammarcus,

I'm super sorry for the late answer. I completely missed your comments.
Thank you for the description! Do you still experience the issue during full reindex?

Do I understand correctly that during full reindex it doesn't pick-up all the products, but saving one-by-one it indexes everything? Did you manage to identify concrete products which have this issue? Thanks a lot for your co-operation! :)

**Comment by JanPetr** [comment]
I tried on the latest versions of M2 and didn't manage to reproduce. So I'm closing the issue.

If you still experience the issue, feel free to re-open.
