### ISSUE TITLE
algolia depedency break fresh install of magento

### ISSUE THREAD

**Issue by springerin** [algolia/algoliasearch-magento-2#146]
if we add the dependency of algolia and launch the install of magento we get the following error:

> Module 'Magento_Catalog':
> Installing data.. exception 'Exception' with message 'Algolia reindexing failed: You need to configure your Algolia credentials in Stores > Configuration > Algolia Search.' in test_m2_algolia/vendor/algolia/algoliasearch-magento-2/Model/Indexer/Category.php:49
> Stack trace:
> #0 test_m2_algolia/vendor/algolia/algoliasearch-magento-2/Model/Indexer/Category.php(88): Algolia\AlgoliaSearch\Model\Indexer\Category->execute(Array)
> #1 test_m2_algolia/vendor/magento/module-indexer/Model/Indexer.php(433): Algolia\AlgoliaSearch\Model\Indexer\Category->executeRow(1)
> #2 test_m2_algolia/vendor/algolia/algoliasearch-magento-2/Model/Indexer/CategoryObserver.php(28): Magento\Indexer\Model\Indexer->reindexRow(1)

Does the module check before launching the index if it's enabled ? Also does it has the dependency on Mage_Catalog defined?
Most automatic deploys use this system so is a blocking issue.

Let me know if you need more details.

**Comment by JanPetr** [comment]
Hello @springerin,

thanks for the report. We will take a look into that.
If you could provide me with more details, like what your composer.json looks like) and what are the exact steps to reproduce the issue, it would really help us.

Thanks!

**Comment by springerin** [comment]
nothing more than already said : 
` composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition testalgolia
composer require algolia/algoliasearch-magento-2
 bin/magento setup:install --base-url=http://testalgolia.dev/ \
        --db-host=localhost --db-name=testalgolia --db-user=testalgolia --db-password=testalgolia \
        --admin-firstname=Admin --admin-lastname=Admin --admin-email=testalgolia@algolia.dev \
        --admin-user=admin --admin-password=testalgolia --language=it_IT \
        --currency=EUR --timezone=Europe/Rome --use-rewrites=1 --session-save=db
`

so is a basic composer.json of a magento 2 project with your module as dependecy

`{
    "name": "bitbull/magento2-project",
    "description": "Magento 2 Project",
    "type": "project",
    "repositories": {
        "magento": {
            "type": "composer",
            "url": "https://repo.magento.com"
        },
        "algolia/algoliasearch-magento-2": {
            "type": "vcs",
            "url": "git@github.com:algolia/algoliasearch-magento-2.git"
        }
    },
    "require": {
        "sjparkinson/static-review": "~4.1",
        "magento/product-community-edition": "2.0.10",
        "algolia/algoliasearch-magento-2": "1.0.5"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}`

**Comment by JanPetr** [comment]
Thanks a lot @springerin, it helps me a lot! I will investigate and come back to you.

**Comment by springerin** [comment]
any news on this? we need to decide if to use it or not in next couple of days so just asking to plan accordingly (unfortunately we don't have the budget to solve this for you).

**Comment by JanPetr** [comment]
Hello @springerin,
I investigated the issue but I didn't find the solution yet.
The issue is that during the Magento 2 installation Magento reindexes all indices. And when it reindexes Algolia, it [throws an exception](https://github.com/algolia/algoliasearch-magento-2/blob/master/Model/Indexer/Category.php#L49), because the Algolia credentials are not filled.

If I'd remove the exception there is no way how to correctly output a message about not-set Algolia credentials, because if I'd change it to simple "echo", the extension would be rejected from Magento Marketplace.

So [currently I'm looking for a way on how to display the message](http://magento.stackexchange.com/questions/156637/magento-2-how-to-display-error-message-in-cli/156659) without taking down the entire application.

If you had any insight or any idea how to output the message gracefully, I'd really appreciate :)

Thanks!

**Comment by springerin** [comment]
i'll try and search myself something and get back to you if i do :)

**Comment by JanPetr** [comment]
Hello @springerin,
I just managed to fix the issue. Feel free to update the extension to `dev-master` and try it out.

**Comment by danslo** [comment]
While this does solve installing Magento when this extension is enabled, it will still spam the console unnecessarily when installing. This is especially noisy while running integration tests. 

So I think instead of just checking for algolia credentials, it should also check if application is installed at all before considering to reindex.
