### ISSUE TITLE
it's normal when searching less text "whi" is to expect more results than searching for more text "whit" but what happened here is that "whit" returned 11 products and "whi" returned only 10 !!!

### ISSUE THREAD

**Issue by dungnv** [algolia/algoliasearch-magento-2#183]
Hi,

it's normal when searching less text "whi" is to expect more results than searching for more text "whit" but what happened here is that "whit" returned 11 products and "whi" returned only 10 !!!

Thanks.

**Comment by JanPetr** [comment]
Hello @dungnv,

yes, this is expected, because of [typo tolerance](https://www.algolia.com/doc/guides/relevance/typo-tolerance/). When you have 3-character query (like `whi`), typo tolerance is not allowed because of [`minWordSizefor1Typo`](https://www.algolia.com/doc/guides/relevance/typo-tolerance/#minwordsizefor1typo) setting which is by default set to 4.
But when you have 4-character query `whit`, 1 typo is allowed for the results. So more results can appear.

**Comment by dungnv** [comment]
Dear @JanPetr ,

How we setting default is false ? because each time we reindex the typo tolerance always set is true.

Thanks.

**Comment by JanPetr** [comment]
Hello @dungnv,

you set typo-tolerance to false in Algolia dashboard?
<img width="451" alt="screenshot 2017-03-22 11 55 13" src="https://cloud.githubusercontent.com/assets/1058144/24194443/6fe25204-0ef6-11e7-8b0a-c714e628e9aa.png">

The extension doesn't override this setting on product reindex.
