### ISSUE TITLE
How to sort/rank category products by position?

### ISSUE THREAD

**Issue by MagePsycho** [algolia/algoliasearch-magento-2#251]
I see many attributes for ranking but not the `position`.
Is this something taken into consideration? 

BTW, many store owner wants to show the products as per position defined by them.

**Comment by JanPetr** [comment]
Hello @MagePsycho,

it's a bit tricky with Algolia. A solution how to do that is described in our FAQ: https://community.algolia.com/magento/faq/#can-i-have-different-ordering-of-products-on-category-pages-with-instant-search-eg-with-visual-merchandiser

Let me know if it helps you. If you need more help, feel free to reopen the issue.

**Comment by MagePsycho** [comment]
Can't we set the default index collection sorted by position?

**Comment by JanPetr** [comment]
When you sort the default index by position you'll lose the order by relevancy. 
But you can use position as custom ranking which would work for category pages.

**Comment by kllee824** [comment]
Where to control the sorting to keep position sorting after product added, the default sorting is reset to entity_id not keeping previously position, it mass the sorting after categories product amendment .....

**Comment by JanPetr** [comment]
Hey @kllee824,

I'm not sure I understand. Could you please provide more information about your use-case? Thanks!

**Comment by peterjaap** [comment]
@JanPetr we're now running into the issue mentioned by @kllee824 as well.

This is our Position (last column) configuration in the backend of a certain category. Default Magento will use the `position` value to sort the products on. It will sort on `position` and within the same `position` values, it will sort on `entity_id`.

![image](https://user-images.githubusercontent.com/431360/49524542-4033cc80-f8ac-11e8-9c79-d5f3de6f91a1.png)

This is when I sort on just `entity_id`;

![image](https://user-images.githubusercontent.com/431360/49524578-52ae0600-f8ac-11e8-896a-cdfc5047c1b4.png)

When I look at the frontend, the sorting matches the `entity_id` sorting, not the `position` sorting;

![image](https://user-images.githubusercontent.com/431360/49524616-622d4f00-f8ac-11e8-8405-0ed8d164c60c.png)

Using the new Algolia Merchandiser isn't an option since this is an anchor category. The Merchandiser will thus show;

![image](https://user-images.githubusercontent.com/431360/49524662-7d985a00-f8ac-11e8-8183-fb735e392296.png)

I tried adding it to the config at Instant Search Resuls Page > Sorts but the option 'position' isn't available there;

![image](https://user-images.githubusercontent.com/431360/49524882-e253b480-f8ac-11e8-98dc-ec9fb3a17b3c.png)

In [your comment](https://github.com/algolia/algoliasearch-magento-2/issues/251#issuecomment-327524478) you say;

> When you sort the default index by position you'll lose the order by relevancy.

Which is perfectly fine, we don't need 'order by relevancy'. But how do we configure this?

**Comment by VincentMarmiesse** [comment]
Why is this issue closed? As far as I know, it's still not possible to sort by `position`.

**Comment by collymore** [comment]
Did anyone find a solution on how to implement the sorting by position?

**Comment by tajveez-73** [comment]
@peterjaap Can you kindly share, Did you came to a solution for sorting by position? Thanks

**Comment by peterjaap** [comment]
@tajveez-73 sorry I don't remember, we no longer work with the client that had this need.

**Comment by yohanespradono** [comment]
Any update on this issue?

**Comment by minhducuit** [comment]
So this part still not work if we use Starter plan or Pro plan @JanPetr , right? Anyone find a solution on how to implement the sorting by position?

**Comment by bsuravech** [comment]
Hi @minhducuit,

Our category merchandising feature is available if you have Query Rules in your Algolia plan. If you have any further questions regarding Query Rules, please contact us through [support@algolia.com](mailto:support@algolia.com). 

https://www.algolia.com/doc/integration/magento-2/merchandising/category-merchandising/?language=php
