### ISSUE TITLE
Algolia is called on non-product page

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-magento-2#288]
If you go to the register page for instance, you'll see that Algolia is still called to load products, even it they're not used. You could come up with a solution to avoid this.

![privacy_policy](https://user-images.githubusercontent.com/1525636/28515783-29e85ff8-705f-11e7-96db-b7d3dc56e605.png)

The DOM is also updated and the content is hidden by CSS.

![privacy_policy](https://user-images.githubusercontent.com/1525636/28518520-72bf0bc4-7068-11e7-987e-4951c3433596.png)

**Comment by danielozano** [comment]
Do you mean that the search adapter tries to "search" on algolia? We had issues with that because there are other extensions using the Search Adapter, so we made more specific the use of algolia's search engine inside the adapter class.

If we are talking about the same problem (I'm not sure) I can share the override we made to avoid this issue.

**Comment by julienbourdeau** [comment]
@danielozano I added a screenshot. I meant that the javascript calls algolia even if we don't need product. Although, your problem seems interesting.

Would you mind submitting a pull request so we can discuss it?
