### ISSUE TITLE
Queue Processor Stuck when processing a lot of items

### ISSUE THREAD

**Issue by BrentRobert** [algolia/algoliasearch-magento-2#676]
**Bug: What is the current behavior?**
When the queue picks up items to process it sets the pid. When it finishes them it removes the entries. When processing a lot of items we see a lot of 'stuck' items. They receive a PID in the table but they do not get processed. The PID stays set, which means they never get picked up again and stay stuck in the table.

**Bug: What is the expected behavior?**
The PID should be removed or not even set?

**Comment by JanPetr** [comment]
Hello @BrentRobert,

it happens when there is an issue in queue configuration - the number of jobs is set too high and it's not possible to process it in time. Could you lower your settings and make sure that the queue_runner indexer is able to finish in 5 minutes?

On the other hand, I understand there should be a process, which "unlocks" the jobs and process it after that. I'll think about it and will come up with a solution. Thank you for the report!

**Comment by 0livier** [comment]
Hi @BrentRobert. Were you able to fix your issue?

**Comment by BrentRobert** [comment]
Sorry for the late response,
The solution of @JanPetr indeed 'fixes' the issue, although there should indeed be an unlock feature to prevent this from happening.

**Comment by peterjaap** [comment]
Nice @JanPetr , good stuff.
