### ISSUE TITLE
Missing `text-over: ellipsis` on the category

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-magento-2#75]
![screen shot 2016-09-22 at 08 58 41](https://cloud.githubusercontent.com/assets/29529/18739290/d1997564-80a2-11e6-8a53-6074f32679b8.png)

**Comment by JanPetr** [comment]
Hey @redox,
actually we have [it there](https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/internals/algoliasearch.css#L638) and it works OK:
<img width="895" alt="screenshot 2016-09-23 10 21 15" src="https://cloud.githubusercontent.com/assets/1058144/18779035/842762de-8177-11e6-974b-87e3d7f3b492.png">

It seems that they did something with their CSS because all texts in products are bold with no highlighting.
