### ISSUE TITLE
Range slider selections do not appear as an applied filter/facet in the layered navigation or catalog search summary

### ISSUE THREAD

**Issue by danemacmillan** [algolia/algoliasearch-magento-2#761]
Any filter/facet applied typically adds itself to the top of the layered navigation or catalog search, accompanied by a clear button, which removes all the applied filters. When a facet is displayed as a range slider, that behaviour is not observed. The base Magento layered navigation adds these filters to the summary with a clear all button. For consistency's sake, range sliders should behave like the others.

**Comment by bsuravech** [comment]
Hi @danemacmillan, 

Thank you for your feedback. Can you confirm for us if you are speaking about the range sliders in instantsearch or the native Magento layered navigation view? I tested my environment's price and rating sliders in instantsearch and they seem to clear with the clear all button. Let us know!

**Comment by damcou** [comment]
Hello there,

I'm not sure to understand what is the issue here, this is what we currently have on our demo store : https://magento2.algolia.com/catalogsearch/result/?q=__empty__&price.USD.default=28%3A74

As you can see, you can remove the two filters related to the price slider separately without having to hit the "clear all" button.

I'll close this issue as it doesn't seem to be one but feel free to reopen it if you have additional questions.

Best.
