### ISSUE TITLE
Custom Yes/No product attributes are indexed as string not boolean

### ISSUE THREAD

**Issue by lumnn** [algolia/algoliasearch-magento-2#767]
**Bug: What is the current behavior?**
- Create custom product attribute with Yes/No type
- Add that attribute to be retrieved with search (not searchable in my case)
- Attribute is beeing indexed and retrieved but it's value is either string "Yes" or "No"

**Bug: What is the expected behavior?**
value of attribute should be boolean `true` or `false`

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.3.1
Algolia Module 1.10

**Comment by damcou** [comment]
Hello @lumnn ;

Thanks for reaching out.
You're right, when you add a "Yes/No" attribute to the indexed attributes list, the values stored inside your indices are "Yes" or "No".
The extension just indexes the value returned by Magento, and in this case, it's strings rather than booleans.

But I can understand that you may want to index boolean instead, you can perform such thing using one of our [backend events](https://www.algolia.com/doc/integration/magento-2/customize/custom-back-end-events/)  (in your case, this would be **algolia_after_create_product_object** ) by changing the value from "No" to false and "Yes" to true before indexing.

Hope that helps.
Best.
Damien
