### ISSUE TITLE
Html_entity_decode voor de request query

### ISSUE THREAD

**Issue by JeroenBoersma** [algolia/algoliasearch-magento-2#769]
We received a security report for one of our customers regarding unescaped HTML-tags in the content which can be set via request parameters.

A request to: `/catalogsearch/result/index/?q=hello<script>alert(1)</script>` will add:
`{...snap...,"request":{"query":"hello<script>alert()<\/script>",...snap...}` to the config instead of the `&lt;` `&gt;` replacements one would expect or the url'encoded `%20` versions.

In our case they try to inject `<esi:...>` blocks, where they try to retrieve secure data. Of coarse they where filtered by our hosting, but it raises questions and that's why I reach out here.

Our research got track of a `html_entiy_decode` of the `q` parameter and that way added to the json configuration.

**Related files:**

https://github.com/algolia/algoliasearch-magento-2/blob/198eda5d1f13403b71a560a5b2dc4cbe4af8046e/Block/Configuration.php#L183

https://github.com/algolia/algoliasearch-magento-2/blob/198eda5d1f13403b71a560a5b2dc4cbe4af8046e/view/frontend/templates/internals/configuration.phtml#L20

Here I see the usage in `instantsearch.js`, which will be send to the minified algoliaBundle.js where I lost track of it. Didn't have time at hand to look into the original bundle or refactor the bundle.

https://github.com/algolia/algoliasearch-magento-2/blob/198eda5d1f13403b71a560a5b2dc4cbe4af8046e/view/frontend/web/instantsearch.js#L158

Because I don't know exactly what is going on in the widgets of Algolia I post the question here where the experts are.

**Questions**

- Is there any reason why the `decoding` is done?
- Is this still needed or can we life without it, which would be my recommendation.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, the related PR is still existing and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
