### ISSUE TITLE
magento 2.1.1 , after algolia installation, backend hang

### ISSUE THREAD

**Issue by shakeshah** [algolia/algoliasearch-magento-2#77]
i am geting
uncaught ReferenceError: algoliaAdminBundle is not defined

and i cannot open anything in backend.

**Comment by JanPetr** [comment]
Hello @shakeshah,
please, what version of the extension are you using? There was an issue with merging JS files in version 1.0.0 and it was fixed in version 1.0.1. https://github.com/algolia/algoliasearch-magento-2/issues/67

If you are still on 1.0.0 I'd suggest you to upgrade or disable JS files merge.

**Comment by shakeshah** [comment]
i am using version 1.0.1, now i am facing issue, on front-end search-box disappeared :(

**Comment by JanPetr** [comment]
If it's the issue, you can change search box selector to you default search box in configuration:
![screenshot 2016-09-29 10 04 34](https://cloud.githubusercontent.com/assets/1058144/18945733/259f9290-862c-11e6-9871-f0585b539518.png)
