### ISSUE TITLE
Disabling autofocus for algolia search box in Magento 2

### ISSUE THREAD

**Issue by aboutzahurul** [algolia/algoliasearch-magento-2#803]
We want to disable autofocus for algolia search box in Magento 2

### Preconditions
1. Magento 2.3
2. algolia/algoliasearch-magento-2 1.11.2

### Expected result
On magento admin backend their should be an option to turn off the autofocus of algolia search box

### Actual result
No option to turn off the search box autofocus

### Solution (temporary)
Maybe it's not the correct way to solve it but for now temporary we are solving it from direct module edit:
https://github.com/algolia/algoliasearch-magento-2/blob/master/Block/Configuration.php
on line 187 we make autofocus false
`'autofocus' => true,`

also on file: https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/instantsearch.js
after on line 231 we added autofocus false
```
			searchBox: {
				container: instant_selector,
				placeholder: algoliaConfig.translations.searchFor,
				autofocus: false
			},
```
more info: https://community.algolia.com/instantsearch.js/v2/widgets/searchBox.html#struct-SearchBoxWidgetOptions-autofocus

Please @algolia add a configuration option on magento admin so we can stop autofocus (autoscroll is another minor issue) if needed. or if you already have a solution show us how to solve it. Thanks.

**Comment by bsuravech** [comment]
Thank you @aboutzahurul for your feedback regarding configurations for autofocus. We have passed it along to our product board for consideration for future improvements.

I would recommend instead of directly modifying the files, to use the frontend hooks provided by the extension to modify or add options to the searchBox widget. I would look at the `beforeWidgetInitialization(allWidgetConfiguration)` event. You can read more about our frontend hooks here:

https://www.algolia.com/doc/integration/magento-2/customize/custom-front-end-events/
