### ISSUE TITLE
Object DOMDocument should be created in Magento 2.1.x

### ISSUE THREAD

**Issue by haiacom** [algolia/algoliasearch-magento-2#842]
**Bug: What is the current behavior?**
run in production mode and Get the error "Object DOMDocument should be created" when access homepage.

**Bug: What is the expected behavior?**
should work normally without error.

**Bug: What is the proposed solution?**
Magento 2.1.x doesn't use resolveArgumentsInRuntime when DI is compiled this will cause the classes with undeclared constructor arguments(which is stored in var/di folder when run setup:di:compile) can not be initiated.
1.11.x use factory to create new  AlgoliaSearch\Client which doesn't work on Magento 2.1.x. The Client class couldn't created because its constructor arguments aren't declared so only "Magento\Framework\ObjectManagerInterface" is passed. see "vendor/magento/framework/ObjectManager/Config/Compiled.php" function getArgurments();

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
I am using 1.11.3 and Magento 2.1.9

**Comment by damcou** [comment]
Hello there,

Unfortunately, we decided to stop maintaining  the extension for Magento 2.1 since Adobe itself has decided to end its support for this version.

What you can do is to downgrade the extension to the latest working one for you (the breaking compatibility occured in v 1.12.0 so it's surprising that your 1.11.3 doesn't seem to work).
But as Adobe has discontinue to support your Magento version, on a global point of view, I'd highly recommend to upgrade your Magento version to the latest one.

Thanks for understanding.
Best.
