### ISSUE TITLE
CMS page changes doesn`t trigger Algolia index 

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#874]
**Bug: What is the current behavior?**
After change content or add new CMS page it isn`t indexed and pushed to Algolia

**Bug: What is the expected behavior?**
After add/update page these changes should update records in Index

**Bug: What is the proposed solution?**
1. Simple solution - Add plugin on resource model and trigger full reindex and push data on Algolia index
2. Improved - Implement reindex for CMS pages as for Products/Categories.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.2.6 / 2.3.1
Algoliasearch 1.10.0 - 1.11.3

**Comment by bsuravech** [comment]
Hi @vmalyk! 

Thanks for filing this issue and submitting a PR! It looks like it is on the right track! While we could reindex all CMS Pages per update/delete event, I think this could be inefficient for those that have a lot of pages and/or update frequently to trigger a full reindex of `algolia_pages`. We should process CMS Pages per item if we are to go the route of observe update/delete events. 

We've created our own internal ticket to continue your work [MAG-263].

Thank you!

**Comment by halvorschmidt** [comment]
Hi @bsuravech !

Do you have an e.t.a for when this bug is fixed?

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, the related PR is still existing and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
