### ISSUE TITLE
Contribution instructions for CircleCI

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#885]
**Bug: What is the current behavior?**
Contribution guide contains irrelevant information about using Travis CI, but all builds are run on CircleCI and fault on environment variables for Magento repository MAGENTO_AUTH_USERNAME and MAGENTO_AUTH_PASSWORD.  

**Bug: What is the expected behavior?**
PR builds shouldn`t fault or should be described how to solve these issues themself

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, it is still in our backlog and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
