### ISSUE TITLE
Algolia overwrites Layered Navigation filters (di.xml)

### ISSUE THREAD

**Issue by Timothy-V** [algolia/algoliasearch-magento-2#897]
**Bug: What is the current behavior?**

/data/web/magento2/vendor/algolia/algoliasearch-magento-2/etc/frontend/di.xml overwrites Magento2 core functionality. Other modules, which depend on the core logic get overwritten by Algolia. In my case, the Mageplaza Layered Nav price slider won't display anymore.

![Screenshot_4](https://user-images.githubusercontent.com/47175711/67291606-12666f00-f4e2-11e9-8a61-a661eb3a84e6.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/47175711/67291539-fb278180-f4e1-11e9-9b03-a339ab5ee1d2.jpg)

**Bug: What is the expected behavior?**
Algolia does not break other layered navigation modules.

**Bug: What is the proposed solution?**
Find a way to get Algolia working without the need for di.xml overwriting the core.
Algolia's facets backend rendering (#[802](https://github.com/algolia/algoliasearch-magento-2/pull/802)) commit introduces the di.xml file. Before that, there were no problems.

I can edit di.xml 

`<item name="price" xsi:type="string">Algolia\AlgoliaSearch\Model\Layer\Filter\Price</item>`

to
`<item name="price" xsi:type="string">Mageplaza\LayeredNavigation\Model\Layer\Filter\Price</item>`

But this edit will only be temporary, since my Algolia is maintained via composer.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.3.2 / AlgoliaSearch 1.12.0

**Comment by vmalyk** [comment]
@damcou and @bsuravech,
The reason of issue it`s 2 preferences in frontend di.xml:
https://github.com/algolia/algoliasearch-magento-2/blob/bd00c4b91664da439d780a704cf0912c02f91d59/etc/frontend/di.xml#L69-L70

If Filter rendering should be work if enabled backend rendering - you can change 2 points:

**Comment by damcou** [comment]
Hello @Timothy-V and @vmalyk , thanks a lot for having spotted this issue, I'll have a look at it asap ;)

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, it is still in our backlog and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
