### ISSUE TITLE
Search result page error.

### ISSUE THREAD

**Issue by luan123z** [algolia/algoliasearch-magento-2#913]
Hello guys, I'm using Magento 2.3.1 with the latest version of Algolia Search.
I've completely configured it but I cannot search for any products.
When I hit the search button, it directs me to the error page.
"there has been an error processing your request"

Below is my log file, can you please have a look?
[1533785306247.txt](https://github.com/algolia/algoliasearch-magento-2/files/3839213/1533785306247.txt)

**Comment by bsuravech** [comment]
Hi @luan123z,

Thanks for reaching out to us. The error message is related to our Facets configuration which is being thrown because this configuration is empty. We will create a pull request to add a condition to check if this is empty to prevent any further errors in this scenario. 

If you would like to configure the Facets, you can do so by going to **Stores > Configuration > Algolia Search > Instantsearch Results Page > Facets**. 

We'll tag this issue in the following PR for your review when it is ready. 

Thanks!

**Comment by luan123z** [comment]
> Hi @luan123z,
> 
> Thanks for reaching out to us. The error message is related to our Facets configuration which is being thrown because this configuration is empty. We will create a pull request to add a condition to check if this is empty to prevent any further errors in this scenario.
> 
> If you would like to configure the Facets, you can do so by going to **Stores > Configuration > Algolia Search > Instantsearch Results Page > Facets**.
> 
> We'll tag this issue in the following PR for your review when it is ready.
> 
> Thanks!

Hi @bsuravech 

I've configured Facets http://prntscr.com/pwo7pa but the error is still there.

However, there is one strange error while saving the config: http://prntscr.com/pwo7u3

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while. In case you still experience the issue after the release, feel free to respond and re-open the issue. Thank you!
