### ISSUE TITLE
Error when running reindex

### ISSUE THREAD

**Issue by luan123z** [algolia/algoliasearch-magento-2#922]
Hello.

I've got this error when running reindex. Can you please have a look? http://prntscr.com/pyxjwl
I'm using Magento 2.3.1.

**Comment by nunomaduro** [comment]
Hi @luan123z,

Thanks for reporting this issue.

Looks like on the line [622](https://github.com/algolia/algoliasearch-magento-2/blob/6772f394da177d4d80886ecc1fb952fc1b174565/Helper/ConfigHelper.php#L622) we may actually end up having a string on `$customRanking` instead of an array:

https://github.com/algolia/algoliasearch-magento-2/blob/6772f394da177d4d80886ecc1fb952fc1b174565/Helper/ConfigHelper.php#L622

@damcou @bsuravech  Could you help us figure this out?

**Comment by damcou** [comment]
Hi @luan123z ,

Could you elaborate more about this issue, could you tell us more about :
- The version of the extension you're using
- The version of Magento you're using
- The version of PHP you're using
- Your configuration regarding custom ranking in the extension's configuration

Thanks in advance.
Best.

**Comment by luan123z** [comment]
Hello @damcou 

I'm using:
- Algolia 1.12.1
- Magento 2.3.1
- PHP 7.2.24
- Custom ranking: http://prntscr.com/pz3h01 ,  http://prntscr.com/pz3h4g

When I click "Save config", another error appears: http://prntscr.com/pz3hjs

**Comment by luan123z** [comment]
Looks like the issue is fixed by adding the ranking here http://prntscr.com/pz3h01 , http://prntscr.com/pz3h4g

**Comment by damcou** [comment]
Thanks for the news.
Yes, to make the indexing working, you need to define attributes and custom rankings.
Here is our official documentation to help you : https://www.algolia.com/doc/integration/magento-2/how-it-works/indexing/?language=php
