### ISSUE TITLE
Error when running queue runner reindex

### ISSUE THREAD

**Issue by luan123z** [algolia/algoliasearch-magento-2#924]
Hello.

I've got this error when running queue runner reindex, can you please let me know why the issue appears? http://prntscr.com/pzcrs3

I'm using Magento 2.3.1, Algolia 1.12.1, PHP 7.2.24

**Comment by damcou** [comment]
@luan123z , could you please have a look at the documentation I suggested in the other thread : https://github.com/algolia/algoliasearch-magento-2/issues/922 and see if the problem persists ?

Thanks in advance.

**Comment by luan123z** [comment]
hi @damcou 
Yes, I've tried that but the issue still persists.

**Comment by bsuravech** [comment]
Hi @luan123z, 

The callback function error you are receiving means that the method `moveIndex` cannot be found. This can be caused by upgrading your extension and the method has either been updated or remove. When upgrading your extension, you should clear your indexing queue to avoid errors like this. 

For now, I would recommend clearing your indexing queue and reindexing your data again to start anew. 

Let me know if that works for you. Thanks.

**Comment by luan123z** [comment]
hi @bsuravech 

Can you please let me know how to clear the indexing queue?

**Comment by 0livier** [comment]
Hi @luan123z .

To clear your queue you can go to Stores > Algolia Search > Indexing Queue page in your Magento backoffice and click the “Clear Queue” button to remove all jobs from the queue.

Additionally, you can also truncate your algoliasearch_queue table in your database. We recommend that if you clear your indexing queue, you should run a full reindex of your data to insure that they are up to date in Algolia.

Let me know if that helped!

Cheers,
