### ISSUE TITLE
Products without reviews show 5-star rating ..

### ISSUE THREAD

**Issue by bmartus** [algolia/algoliasearch-magento-2#952]
**Bug: What is the current behavior?**
Products with no reviews show a 5-star rating.

![image](https://user-images.githubusercontent.com/4819899/70943103-ac93f080-2015-11ea-953a-1702cb15fd7f.png)

**Bug: What is the expected behavior?**
Products with no reviews should show a 0-star rating (or hide the stars altogether?).

![image](https://user-images.githubusercontent.com/4819899/70943130-bcabd000-2015-11ea-881c-6c489d87b2a6.png)

**Bug: What is the proposed solution?**
Products `rating_summary` should index `0` rather than `null` when they have no reviews.

**What is the version of Magento and of Algolia extension you are using?**
Magento Commerce 2.3.3
Algolia 1.12.1

**Comment by Serializator** [comment]
When I try to reproduce this on Magento 2.3.3 with Algolia 1.12.1, without any other additional modules, it seems to only render the star rating if there is at least 1 review, both on the category overview page and the search result page.

Could you maybe explain in a bit more detail how to reproduce this?

**Comment by damcou** [comment]
Hello @bmartus and @Serializator ,

As @Serializator suggested, I would be intestered to know how to reproduce it.
Do you have any insights about it ?

Thanks in advance.
 Best.

**Comment by bmartus** [comment]
I am able to see the issue on the magento2 algolia demo site ..

If you [search for "v-neck"](https://magento2.algolia.com/catalogsearch/result/?q=v-neck), you'll see some products with reviews that have the proper star ratings showing:

![Screenshot from 2019-12-30 11-28-47](https://user-images.githubusercontent.com/4819899/71592916-a31b8580-2af7-11ea-8140-c2999fb9e183.png)

And products with no reviews, that have what appears to be a 5-star rating, rather than 0-star:

![Screenshot from 2019-12-30 11-28-53](https://user-images.githubusercontent.com/4819899/71592924-a747a300-2af7-11ea-8d06-94227f51b04d.png)

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, it is still in our backlog and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
