### ISSUE TITLE
Indexed products remove from Algolia

### ISSUE THREAD

**Issue by annaconv** [algolia/algoliasearch-magento-2#953]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Indexed products remove from Algolia.

For example:
1) I have product in Magento with id 5705:
![1](https://user-images.githubusercontent.com/43742869/70993083-4c1bb680-20dc-11ea-94ce-aed16fa97a70.png)

2) It price is not reindexed yet:
![2](https://user-images.githubusercontent.com/43742869/70993157-71102980-20dc-11ea-8c90-e5556d228342.png)

3) Cron created job in queue:
![image](https://user-images.githubusercontent.com/43742869/70993189-84bb9000-20dc-11ea-8ccb-c5ee4fe2e302.png)

4) I run algolia_queue_runner for this products ids:
![image](https://user-images.githubusercontent.com/43742869/70993222-9735c980-20dc-11ea-864a-d50d450be46e.png)

5) Product collection query is:
![image](https://user-images.githubusercontent.com/43742869/70993239-a3ba2200-20dc-11ea-813e-b768606ae149.png)

6) Collection items not contains product with entity_id=5705, because it price is not reindexed yet:
![image](https://user-images.githubusercontent.com/43742869/70993254-acaaf380-20dc-11ea-8408-29f6cfc4b451.png)

**Bug: What is the expected behavior?**
Product should not remove when it price is not reindexed yet

**Bug: What is the proposed solution?**
Product that price is not reindexed yet going to remove from Algolia, because it’s not presented in collection of products that **inner** joins catalog_product_index_price.
You can use **left** join catalog_product_index_price to load all existing products, because you use \Algolia\AlgoliaSearch\Helper\Entity\ProductHelper::getObject in \Algolia\AlgoliaSearch\Helper\Data::getProductsRecords, that can load prices from object if price values in collection is null

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Algolia 1.12.1
Magento 2.2.6 Commerce

**Comment by damcou** [comment]
Hello @annaconv ,

I had a look at this issue, and indeed I can reproduce it when the product prices are not listed in the table `catalog_product_index_price` , but for this I had to delete them manually in the database. 

Could you please tell us what is the mode of your product price indexer (I guess it's set to "on schedule" ?) 

In the meantime, I see 2 ways to solve this : 
- The method which adds the join to the `catalog_product_index_price` is the `addFinalPrice` from the `ProductHelper` : https://github.com/algolia/algoliasearch-magento-2/blob/develop/Helper/Entity/ProductHelper.php#L285. Removing it doesn't seem to affect price indexing, could you please to try to remove in on your side to see if it solves the issue.
- Magento provides a way to use a `LEFT JOIN` rather than a `INNER JOIN` inside its `\Magento\Catalog\Model\ResourceModel\Product\Collection::productLimitationPrice` : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L1908-L1985 . Unfortunately it's protected and it doesn't seem to be possible to use a `LEFT JOIN` without having to override the function `_productLimitationJoinPrice` that calls it.

Let us know what you think about it. 
Best.

**Comment by annaconv** [comment]
Hello @damcou ,
Yes, price indexer and algolia products indexer in scheduled mode.
Price indexer remove related rows before start. If algolia_queue_runner is running at same time we've got an issue.
Thanks, we will check provided solutions.

**Comment by annaconv** [comment]
Hello @damcou ,
Looks like you first solution is applicable for us.

Thank you!
