### ISSUE TITLE
"Display Product Prices In Catalog" with "Including and Excluding Tax"

### ISSUE THREAD

**Issue by Serializator** [algolia/algoliasearch-magento-2#959]
**Bug: What is the current behavior?**
When you have "Display Product Prices In Catalog" set to "Including and Excluding Tax" the autocomplete will use the price excluding tax and not take into account the price including tax (or give the end-user the choice which one to use in the autocomplete).

**Bug: What is the expected behavior?**
"Including Tax" and "Excluding Tax" to be configurable for the autocomplete if "Display Product Prices In Catalog" is set to "Including and Excluding Tax".

**Bug: What is the proposed solution?**
I'd propose a system configuration to be added to "Stores > Configuration > Sales > Tax > Price Display Settings" underneath "Display Product Prices In Catalog".

A select with "Including Tax" and "Excluding Tax" as its options, only shown if "Display Product Prices In Catalog" is set to "Including and Excluding Tax" with a default value of "Excluding Tax" (same as the default value for "Display Product Prices In Catalog").

If it's possible to locate the system configuration more towards Algolia, in the same section as Algolia for example, that would be great. But I think that keeping the configuration as close to the "reason why it exists", being the "Display Product Prices In Catalog" configuration is in this case the best choice.

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 2.3.3 & Algolia 1.12.1

**Comment by jcodo** [comment]
:+1:

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
