### ISSUE TITLE
Wrong URLs indexed on Magento 2.3.3

### ISSUE THREAD

**Issue by extroniks** [algolia/algoliasearch-magento-2#966]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

Reindex on multi website causes wrong product urls from wrong websites to be indexed.

**Bug: What is the expected behavior?**

Correct urls are indexed.

**Bug: What is the proposed solution?**

Remove the following preference for Magento 2.3.3:
`<preference for="Magento\Catalog\Model\Product\Url" type="Algolia\AlgoliaSearch\Model\Product\Url" />`

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Magento 2.3.3, latest Algolia extension (1.12.1).

**Comment by magegirl** [comment]
UP same problem too

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
