### ISSUE TITLE
Add to cart Ajax not working in Instant search page

### ISSUE THREAD

**Issue by baljinderimpinge** [algolia/algoliasearch-magento-2#979]
Hello Support @JanPetr @damcou @bsuravech @phirunson @unicoder88 @peterjaap ,

I am getting issue on Product listing page. here below is the scenario:
1) Open any Product Listing page and filter with any brand.
2) Then click on add to cart button of any simple product.
3) It will reload the page first time and removed the filters. But it should add product to cart using ajax and filter get selected. If I repeat this process in second time, then It is working fine.
Please check https://magento2.shisha-koenig.ch/e-shisha/e-zigaretten.html?aw_shopbybrand_brand=InSmoke
Please check the screenshot https://prnt.sc/r240x7 
Let me know a suitable fix for this issue.

Thanks and Regards

**Comment by peterjaap** [comment]
Here's something to point you in the right direction.

On first load, the `form` element of any add to cart button has two listeners on the submit event - see screenshot in the developer console (`document` and `form`).

![image](https://user-images.githubusercontent.com/431360/74517404-57d7fd80-4f12-11ea-85bc-7fa343c809f7.png)

After filtering (any filter), the items are redrawn by the Algolia extension but now there is only one listeners on the submit event, just the `document` so the `form` listener is gone. I'm not sure where this is set. This listener should be re-added after redrawing the items.

![image](https://user-images.githubusercontent.com/431360/74517439-645c5600-4f12-11ea-850a-249b2c2722b4.png)

**Comment by baljinderimpinge** [comment]
Hello @peterjaap,

Thanks For the update. 

As per my understanding , I need to re-initialise the add to cart form after the ajax filter complete?
Can you please support me, how to solve this issue?

**Comment by lornacodes** [comment]
I also have the same issue. 

Should the ajax add to cart should still work after selecting the filters. Currently, the page reloads and you lose the filters. 

Is there any solution for this?

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
