### ISSUE TITLE
"Move JS code to the bottom of the page" javascript error algoliaBundle is not defined

### ISSUE THREAD

**Issue by webtekindo** [algolia/algoliasearch-magento-2#981]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

When we set "Move JS code to the bottom of the page" to "Yes"

Error javascript on every page:

Uncaught ReferenceError: algoliaBundle is not defined

**Bug: What is the expected behavior?**

No javascript error

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**

Algolia 1.13.0
Magento 2.3.3

**Comment by danemacmillan** [comment]
I can confirm this as well. We're undergoing migration work to `2.3.3` and this error appears in the developer console. Oddly, it does not seem to break functionality, though errors are no good, so it's better to fix this.

**Comment by cafefin** [comment]
Yes, same issue. This problem occurs with Magento 2.3.3 and Algolia 1.12.1.  I noticed that every js works well, only the algolia part is an error message

**Comment by cafefin** [comment]
As far as I know, Magento 2.3.3 only supports IE 11 or later.
So if it's not needed, you can remove it, or override the js from using DOMContentLoaded to OnLoad.  Its working

**Comment by dsjacobsen** [comment]
Same problem on Magento 2.3.4 tested with Algolia 1.13.0, 1.13.1 and 2.0.0.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
