### ISSUE TITLE
Conflict issue 

### ISSUE THREAD

**Issue by aartipatel6495** [algolia/algoliasearch-magento-2#987]
Hello,

I have debug Algolia search extension and those error coming from below file:

algolia/algoliasearch-magento-2/view/frontend/templates/autocomplete/category.phtml

When I comment below code and error is gone  but category search is not working
Code: {{#image_url}}
        <div class="thumb">
            <img src="{{{image_url}}}" alt="{{{name}}}" />
        </div>
        {{/image_url}}

I have also check image related from welt pixel search optimization module but there is not any this type of code available. Can you please check it what is the exact issue? Or which image_url code working for the category section?

**Comment by bsuravech** [comment]
Hi @aartipatel6495,

Thanks for submitting and my apologies for the delay in response. As I mentioned in Issue #995, our extension is currently not compatible the Welt Pixel extension for layered navigation. 

Regarding your issue with the autocomplete section for category, can you show us the exact error you are receiving? Can you send us over a screenshot? We are closing this issue on Github but if your issue is still persistent, please send us your error messages and screenshots over to us at [support@algolia.com](mailto:support@algolia.com). Thank you!
