### ISSUE TITLE
Incorrect behavior of categories filter

### ISSUE THREAD

**Issue by annaconv** [algolia/algoliasearch-magento-2#989]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
There is two wrong cases:
Case 1:
1) "Replace categories page" setting is enabled in Magento
2) Categories is shown as hierarchical menu on search results page
3) We have next categories structure:
Category1 -> Category1.1
Category1 -> Category1.2
Category2 -> Category2.1
4) Product1 exists in "Category1 -> Category1.1" and "Category2 -> Category2.1"
5) Go to the "Category1 -> Category1.1" category page using top menu link
6) "Category1 -> Category1.1", "Category2" will be shown in category filters that doesn't make sense. Only "Category1 -> Category1.1" should be shown

This leads to case 2:
After reproducing steps 1-6 from case 1, do the next:
7) Navigate to "Category2 -> Category2.1" using category filter
8) Product1 will be shown on search results page. Go to the Product1 page
9) "Category1 -> Category1.1" will be shown in breadcrumbs, that looks wrong, because we go to product page from "Category2 -> Category2.1"

**Bug: What is the expected behavior?**
In both cases in step 6 only current category should be shown ("Category1 -> Category1.1", not "Category2"). 
In second case steps 7-9 should not be possible to reproduce.

**Bug: What is the proposed solution?**
Fix hierarchical menu to filter values relevant to current filter.

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed configuration entry? The new option to add? What is the behavior?**

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Algolia 1.12.1
Magento 2.2.6 Commerce

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
