### ISSUE TITLE
Algolia Backend rendering / User Agent and Page Cache issue in Magento

### ISSUE THREAD

**Issue by abhimotee** [algolia/algoliasearch-magento-2#991]
Hello,

We are currently facing an issue with the Magento page cache and the **_Allow backend rendering for User Agents_** Algolia setting.

_Current main Algolia settings:_

- Enable Instant Search Results Page: Yes
- Prevent backend rendering: Yes
- Prevent backend rendering for: All categories
- Allow backend rendering for User Agents: GoogleBot, Bingbot

_Additional details:_

- Magento version: 2.3.3
- Algolia module version: 1.13.0
- Page Cache: Magento Built-in cache. Not tested on Varnish or Fastly
- User agent server configuration: correct HTTP_USER_AGENT is available i.e. not stripped in any way and can be read by the module's code.

_Steps to reproduce issue:_

1. Load a category page with user-agent: GoogleBot
2. Backend rendering happening and then Instant Search Page takes over as per Allow backend rendering for User Agents configuration.
3. Then load the same category page with normal browser user-agent.

_Issue details:_

You are served a server cached version of what GoogleBot saw in step 1-2, even though your user-agent is no longer GoogleBot. 

We expected a normal user-agent to be served only the instant search page with no backend rendering happening. The page caching should be per rendering context which seems to be handled by class: Plugin/RenderingCacheContextPlugin.php in the Algolia Magento module. However, this is not happening or maybe there is a known limitation with this.

Also, please note that if a category page has not been loaded with any user-agent allowed for backend rendering, then all other users will see only the Instant Search Page correctly. The issue starts to appear once one of allowed user agents for backend rendering loads the same page.

Note that we confirmed it is server page cache related and not browser cache related. Once the server cache is cleared, the user will see the Instant Search Page only again.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M2 community board](https://github.com/algolia/algoliasearch-magento-2/projects/1).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!

**Comment by bsuravech** [comment]
Followed up by HS#257143.
