### ISSUE TITLE
Indexing Issue

### ISSUE THREAD

**Issue by devkrishan2018** [algolia/algoliasearch-magento-2#996]
We are facing some issue with this module. When we enable Alogolia_Search module the indexing stops working.

**Comment by bsuravech** [comment]
Hi @devkrishan2018,

Thanks for reaching out. Can you provide more information about any errors you are receiving? Please provide the steps for reproduction. Thanks.

**Comment by devkrishan2018** [comment]
Please enable Algolia_Search module and then run php bin/magento indexer:reindex

**Comment by bsuravech** [comment]
@devkrishan2018 Is there any output when you run the command? Can you please provide any errors you are receiving.

**Comment by devkrishan2018** [comment]
Hello support

I've got this error to appear on the SSH Terminal when I run reindex.
https://user-images.githubusercontent.com/45222636/77141056-93ca2980-6aa1-11ea-8ea5-e4d6273aacac.png

**Comment by bsuravech** [comment]
@devkrishan2018 did you recently upgrade your extension? I would recommend either case that you clear your indexing queue before performing the reindex again. You can read more about this call_user_func_array() error here: 

https://www.algolia.com/doc/integration/magento-2/getting-started/upgrading/?language=php#after-upgrading

**Comment by devkrishan2018** [comment]
New error is occured.
https://user-images.githubusercontent.com/45222636/77153848-8f613900-6ac0-11ea-97ba-ae2aa6a334fa.png

**Comment by bsuravech** [comment]
Hi @devkrishan2018,

My apologies for the delay in response. According to your screenshot, it seems that the data being indexed has some issues converting to JSON. You could use our Reindex SKU form in the extension to troubleshoot a product to see if there are any issues you can ascertain from there. 

Were you able to resolve your issue since then? If you are experiencing further issues, please reach out to us at [support@algolia.com](mailto:support@algolia.com) with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
